version: '3.8'

services:
  # 1. El túnel de Cloudflare (Conexión segura saliente)
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: tunnel_cloudflare
    command: tunnel --url http://proxy-reverse:80
    networks:
      - red_proyecto
    restart: always

  # 2. El Proxy Inverso Nginx
  proxy-reverse:
    image: nginx:alpine
    container_name: proxy_reverse_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - red_proyecto
    depends_on:
      - mi-servidor-python

  # 3. Tu aplicación Python (Se construye dinámicamente con tu Dockerfile)
  mi-servidor-python:
    build: .
    container_name: contenedor_backend_python
    # Al estar en la misma red de Docker, sus credenciales y tokens quedan aislados del exterior
    networks:
      - red_proyecto

networks:
  red_proyecto:
    driver: bridge
